#MobHunt Configuration

world: 'world'

mobList:
  ZOMBIE : 1
  SKELETON : 2
  CREEPER : 2
  ENDERMAN : 3
  ZOMBIE_VILLAGER : 3

rewards:
  first:
    - give %player% diamond 1
  second:
    - give %player% gold 1
  third:
    - give %player% iron 1